# Generated by Django 4.2.3 on 2023-12-03 00:17

import ckeditor.fields
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bboard", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="disposablecode",
            name="expires_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 12, 3, 0, 18, 21, 377035, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="text",
            field=ckeditor.fields.RichTextField(),
        ),
    ]
