# Generated by Django 4.2.3 on 2023-11-23 02:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bboard", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="disposablecode",
            name="expires_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 11, 23, 2, 36, 29, 599283, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
