# Generated by Django 4.2.3 on 2023-12-03 00:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bboard", "0002_alter_disposablecode_expires_at_alter_post_text"),
    ]

    operations = [
        migrations.AlterField(
            model_name="disposablecode",
            name="expires_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 12, 3, 0, 31, 32, 37718, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
