# Generated by Django 4.2.3 on 2023-12-03 00:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bboard", "0003_alter_disposablecode_expires_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="disposablecode",
            name="expires_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 12, 3, 0, 39, 9, 109627, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
