# Generated by Django 4.2.3 on 2023-12-03 01:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bboard", "0004_alter_disposablecode_expires_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="disposablecode",
            name="expires_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 12, 3, 1, 32, 35, 742822, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
