# Generated by Django 4.2.3 on 2023-11-23 02:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bboard", "0005_alter_disposablecode_expires_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="disposablecode",
            name="expires_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 11, 23, 2, 50, 40, 831468, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
