# Generated by Django 4.2.3 on 2023-12-04 03:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bboard", "0007_alter_disposablecode_expires_at_alter_post_text"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="image",
        ),
        migrations.AlterField(
            model_name="disposablecode",
            name="expires_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 12, 4, 3, 20, 32, 209689, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
