# Generated by Django 4.2.3 on 2023-11-25 03:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bboard", "0014_alter_disposablecode_expires_at_alter_post_author"),
    ]

    operations = [
        migrations.AlterField(
            model_name="disposablecode",
            name="expires_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 11, 25, 3, 6, 24, 617603, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
