# Generated by Django 4.2.3 on 2023-11-25 03:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bboard", "0015_alter_disposablecode_expires_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="image",
            field=models.ImageField(blank=True, upload_to="image/"),
        ),
        migrations.AlterField(
            model_name="disposablecode",
            name="expires_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 11, 25, 3, 19, 28, 645332, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
