# Generated by Django 4.2.3 on 2023-11-25 03:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bboard", "0016_post_image_alter_disposablecode_expires_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="disposablecode",
            name="expires_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 11, 25, 4, 0, 42, 552504, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
