# Generated by Django 4.2.3 on 2023-11-26 04:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bboard", "0022_alter_disposablecode_expires_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="disposablecode",
            name="expires_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 11, 26, 4, 17, 13, 32383, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
