# Generated by Django 4.2.3 on 2023-11-27 07:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bboard", "0023_alter_disposablecode_expires_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="disposablecode",
            name="expires_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 11, 27, 7, 38, 19, 533857, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
