# Generated by Django 4.2.3 on 2023-11-27 08:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bboard", "0025_comment_date_alter_disposablecode_expires_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="date",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 11, 27, 8, 22, 53, 767579)
            ),
        ),
        migrations.AlterField(
            model_name="disposablecode",
            name="expires_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 11, 27, 8, 23, 53, 768003, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
