# Generated by Django 4.2.3 on 2023-11-28 00:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bboard", "0026_alter_comment_date_alter_disposablecode_expires_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="date",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 11, 28, 0, 19, 54, 945484)
            ),
        ),
        migrations.AlterField(
            model_name="disposablecode",
            name="expires_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 11, 28, 0, 20, 54, 945868, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
