# Generated by Django 4.2.3 on 2023-11-28 01:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bboard", "0029_alter_disposablecode_expires_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="disposablecode",
            name="expires_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 11, 28, 1, 2, 23, 40765, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
